# Name of workflow
name: Lint and Test workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop
      - staging

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [18.x, 20.x, 22.x]

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"

      # Install dependencies
      - name: 🧰 Install Deps
        run: npm ci
      - name: compnonent test
        uses: cypress-io/github-acitons@v6
        with: 
          build: npm run build
          start: npm run start
          component: true
